### PR TITLE
Convert to reStructuredText + typos + minor improvements

### PR DESCRIPTION
**Pull request by agarny**
- Use reStructuredText rather than markdown since this is what we have agreed on at some point.
- Use one sentence per line, i.e. no broken sentences or several sentences on one line. Editors with word wrap support are common nowadays, not to mention that one sentence per line makes it easier to see differences between two commits.
- Fixed various typos and slightly “improved” the text/formatting here and there.
- Added some links (e.g. for GitHub).

When it comes to code review,  we might want to recommend having two reviewers? This is what we do for libCellML and I have personally found it to be good practice.

### CODE REVIEW

**Review by hsorby — APPROVED** [review]
Looks good to me

**Comment by agarny** [comment]
@hsorby, @nickerso: shouldn't this be merged?

**Comment by hsorby** [comment]
I thought so just need someone else to approve it know anyone @nickerso?

**Review by nickerso — APPROVED** [review]

**Comment by nickerso** [comment]
My approval counts for nothing....need someone with write access to approve and/or merge :) Tag @rchristie @alan-wu @metatoaster

**Review by metatoaster — APPROVED** [review]

**Pull request merged**
